# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

enabled: true

connectionManager: test

clusterName: test
clusterNamespace: test

logLevel: 1

dnsSuffix: "mcm.svc"
plugins: "kube-service"
istioIngressGateway: ""
istioServiceEntryRegistryNamespace: ""

serviceRegistry:
  image:
    repository: ibmcom/mcm-service-registry
    tag: 3.2.0
    pullPolicy: IfNotPresent

coredns:
  image:
    repository: ibmcom/coredns
    tag: 1.2.6.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 70Mi
    limits:
      cpu: 500m
      memory: 170Mi

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

imagePullSecret: null

logLevel: 5
