# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

enabled: true

connectionManager: test

clusterName: test
clusterNamespace: test

logLevel: 1

dnsSuffix: "mcm.svc"
plugins: "kube-service"
istioIngressGateway: ""
istioServiceEntryRegistryNamespace: ""

coredns:
  resources:
    requests:
      memory: 70Mi
    limits:
      memory: 170Mi

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

logLevel: 5

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    coredns: quay.io/open-cluster-management/coredns:1.2.6.1
    multicloud_manager: quay.io/open-cluster-management/multicloud-manager:3.2.0