{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" -}}

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: {{ template "iamPolicyController.scc" . }}
  labels:
    app: {{ template "iamPolicyController.fullname" . }}
    chart: {{ template "iamPolicyController.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: []
requiredDropCapabilities: []
readOnlyRootFilesystem: false
# allowedProcMountTypes: runtime/default
priority: 1
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ template "iamPolicyController.serviceAccount" . }}
volumes:
- '*'

{{- end -}}
