# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

enabled: true
replicas: 1
globalView:
  enabled: false
  collectorLabels: "mcm.ibm.com/globalview=true"
clusterName: null
clusterNamespace: null

image:
  repository: ibmcom/mcm-operator
  tag: 3.2.0
  pullPolicy: IfNotPresent

bootstrapConfig:
  hubSecret: kube-system/klusterlet-bootstrap

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

imagePullSecret: null

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

logLevel: 5
