org: open-cluster-management
replicas: 1

args:
  frequency: 30
  verbosity: 0

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

nodeSelector: {}

clusterNamespace: ""

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists

leaseController: 
  name: iam-policy-controller
  resources:
    requests:
      memory: "32Mi"
      cpu: "20m"
    limits:
      memory: "256Mi"
      cpu: "500m"

global:
  imagePullPolicy: Always
  imagePullSecret: null
  imageOverrides:
    iam_policy_controller: quay.io/open-cluster-management/iam-policy-controller:1.0.0
    klusterlet_addon_lease_controller: ""