{{- if .Values.alertmanager.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}-alertmanager
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-alertmanager
spec:
  ports:
    - name: web
      port: {{ .Values.alertmanager.port }}
      protocol: TCP
    {{- if .Values.tls.enabled }}
      targetPort: 8443
    {{- else }}
      targetPort: 9093
    {{- end }}
  selector:
    alertmanager: {{ template "prometheus.fullname" . }}-alertmanager
    component: alertmanager
    release: {{ .Release.Name }}
  type: {{ .Values.alertmanager.service.type }}
{{- end -}}