{{- if .Values.collectdExporter.enabled -}}
# Licensed Materials - Property of IBM
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}
    component: collectdexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-collectdexporter
spec:
  selector:
    matchLabels:
      app: {{ template "prometheus.fullname" . }}
      component: collectdexporter
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        chart: {{ .Chart.Name }}
        component: collectdexporter
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      name: {{ template "prometheus.fullname" . }}-collectdexporter
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
{{- if eq .Values.mode "managed" }}
      priorityClassName: system-cluster-critical
{{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
        - image: {{ .Values.collectdExporter.image.repository }}:{{ .Values.collectdExporter.image.tag }}
          name: collectd-exporter
          resources:
{{ toYaml .Values.collectdExporter.resources | indent 12 }}
          securityContext:
            runAsUser: 65534
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          args: [ "--collectd.listen-address=:25826" ]
        {{- if .Values.collectdExporter.probe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9103
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9103
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
        {{- end }}
      {{- if .Values.tls.enabled }}
        - name: router
          image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
              add: [CHOWN, NET_ADMIN, NET_RAW, LEASE, SETGID, SETUID]
          resources:
{{ toYaml .Values.router.resources | indent 12 }}
          command: ["/opt/ibm/router/entry/entrypoint.sh"]
          volumeMounts:
            - mountPath: "/opt/ibm/router/conf"
              name: router-config
            - mountPath: "/opt/ibm/router/caCerts"
              name: monitoring-ca-certs
            - mountPath: "/opt/ibm/router/certs"
              name: monitoring-certs
            - mountPath: "/opt/ibm/router/entry"
              name: router-entry
      {{- end }}
      volumes:
      {{- if .Values.tls.enabled }}
        - name: router-config
          configMap:
            name: {{ template "prometheus.fullname" . }}-exporter-router-nginx-config
            items:
              - key: collectdexporter.nginx.conf
                path: nginx.conf
        - name: monitoring-ca-certs
          secret:
            secretName: {{ .Values.tls.ca.secretName }}
        - name: monitoring-certs
          secret:
          {{- if .Values.tls.exporter.existingSecretName }}
            secretName: {{ .Values.tls.exporter.existingSecretName }}
          {{- else }}
            secretName: {{ template "monitoring.fullname" . }}-exporter-certs
          {{- end }}
        - name: router-entry
          configMap:
            name: {{ template "monitoring.fullname" . }}-router-entry-config
            defaultMode: 0744
      {{- end }}
{{- end -}}
