{{- if .Values.elasticsearchExporter.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}
    component: elasticsearchexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-elasticsearchexporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        chart: {{ .Chart.Name }}
        component: elasticsearchexporter
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: elasticsearch-exporter
        productVersion: 1.0.2
        productID: none
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
{{- if eq .Values.mode "managed" }}
      priorityClassName: system-cluster-critical
{{- end }}
{{ include "monitoring.affinity" . | indent 6 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      containers:
        - image: {{ .Values.elasticsearchExporter.image.repository }}:{{ .Values.elasticsearchExporter.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            runAsUser: 65534
            allowPrivilegeEscalation: false
          name: elasticsearchexporter
          resources:
{{ toYaml .Values.elasticsearchExporter.resources | indent 12 }}
          ports:
        {{- if .Values.tls.enabled }}
          - containerPort: 8443
        {{- else }}
          - containerPort: 9108
        {{- end }}
            name: metrics
          args:
            - -es.uri={{ .Values.elasticsearchExporter.esUri }}
        {{- if .Values.elasticsearchExporter.tls.enabled }}
            - -es.ca=/opt/ibm/monitoring/ca/{{ .Values.elasticsearchExporter.tls.ca.certFieldName }}
            - -es.client-cert=/opt/ibm/monitoring/clientCert/{{ .Values.elasticsearchExporter.tls.client.certFieldName}}
            - -es.client-private-key=/opt/ibm/monitoring/clientCert/{{ .Values.elasticsearchExporter.tls.client.keyFieldName }}
          volumeMounts:
            - mountPath: "/opt/ibm/monitoring/ca"
              name: ca-cert
            - mountPath: "/opt/ibm/monitoring/clientCert"
              name: client-cert
        {{- end }}
        {{- if .Values.elasticsearchExporter.probe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9108
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9108
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
        {{- end }}
      {{- if .Values.tls.enabled }}
        - name: router
          image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.router.resources | indent 12 }}
          command: ["/opt/ibm/router/entry/entrypoint.sh"]
          volumeMounts:
            - mountPath: "/opt/ibm/router/conf"
              name: router-config
            - mountPath: "/opt/ibm/router/caCerts"
              name: monitoring-ca-certs
            - mountPath: "/opt/ibm/router/certs"
              name: monitoring-certs
            - mountPath: "/opt/ibm/router/entry"
              name: router-entry
      {{- end }}
      volumes:
      {{- if .Values.elasticsearchExporter.tls.enabled }}
        - name: ca-cert
          secret:
            secretName: {{ .Values.elasticsearchExporter.tls.ca.secretName }}
        - name: client-cert
          secret:
          {{- if .Values.elasticsearchExporter.tls.client.existingSecretName }}
            secretName: {{ .Values.elasticsearchExporter.tls.client.existingSecretName }}
          {{- else }}
            secretName: {{ template "monitoring.fullname" . }}-elasticsearch-exporter-client-certs
          {{- end }}
      {{- end }}
      {{- if .Values.tls.enabled }}
        - name: router-config
          configMap:
            name: {{ template "prometheus.fullname" . }}-exporter-router-nginx-config
            items:
              - key: elasticsearchexporter.nginx.conf
                path: nginx.conf
        - name: monitoring-ca-certs
          secret:
            secretName: {{ .Values.tls.ca.secretName }}
        - name: monitoring-certs
          secret:
          {{- if .Values.tls.exporter.existingSecretName }}
            secretName: {{ .Values.tls.exporter.existingSecretName }}
          {{- else }}
            secretName: {{ template "monitoring.fullname" . }}-exporter-certs
          {{- end }}
        - name: router-entry
          configMap:
            name: {{ template "monitoring.fullname" . }}-router-entry-config
            defaultMode: 0744
      {{- end }}
{{- end -}}
