{{- if and (not .Values.elasticsearchExporter.tls.client.existingSecretName) .Values.elasticsearchExporter.tls.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "monitoring.fullname" . }}-elasticsearch-exporter-client-certs
spec:
  secretName: {{ template "monitoring.fullname" . }}-elasticsearch-exporter-client-certs
  issuerRef:
    name: {{ .Values.tls.issuer }}
    kind: {{ .Values.tls.issuerKind }}
  commonName: "elasticsearch-exporter"

{{- end -}}
