{{- if .Values.tls.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-exporter-router-nginx-config
data:
 elasticsearchexporter.nginx.conf: |-
    {{ include "router.nginx.config" (list 9108 8443 .Values.tls.ca.certFieldName .Values.tls.sslCiphers) }}
 kubestateexporter.nginx.conf: |-
    {{ include "router.nginx.config" (list 8080 8443 .Values.tls.ca.certFieldName .Values.tls.sslCiphers) }}
 collectdexporter.nginx.conf: |-
    {{ include "router.nginx.config" (list 9103 8443 .Values.tls.ca.certFieldName .Values.tls.sslCiphers) }}
 nodeexporter.nginx.conf: |-
    {{ include "router.nginx.config" (list .Values.nodeExporter.listenPort .Values.nodeExporter.port .Values.tls.ca.certFieldName .Values.tls.sslCiphers .Values.nodeExporter.healthyPort) }}
{{- end -}}