{{- if .Values.grafana.enabled -}}
# Licensed Materials - Property of IBM
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}
    component: grafana
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "grafana.fullname" . }}-grafana-crd-entry
data:
  run.sh: |
    #!/bin/bash
    FLAG=false
    while [[ $FLAG == false ]]; do
    {{- if .Values.tls.enabled }}
      curl -k --connect-timeout 10 https://127.0.0.1:{{ .Values.clusterPort }}/api
    {{- else }}
      curl -k --connect-timeout 10 http://127.0.0.1:3000/api
    {{- end }}
      if [[ $? == 0 ]]; then
        FLAG=true
        echo "Grafana process started"
      fi
    done

    /grafana-dashboard-crd
{{- end -}}
