{{- if .Values.nodeExporter.enabled -}}
# Licensed Materials - Property of IBM
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    {{- if .Values.tls.enabled }}
    prometheus.io/scheme: 'https'
    {{- end }}
    skip.verify: 'true'
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nodeexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-nodeexporter
spec:
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.port }}
      protocol: TCP
    {{- if .Values.tls.enabled }}
      targetPort: {{ .Values.nodeExporter.port }}
    {{- else }}
      targetPort: {{ .Values.nodeExporter.listenPort }}
    {{- end }}
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: nodeexporter
    release: {{ .Release.Name }}
  type: ClusterIP

{{- end -}}
