{{- if and .Values.prometheus.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        chart: {{ .Chart.Name }}
        component: prometheus-operator
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: prometheusoperator
        productVersion: v0.31.1
        productID: none
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
{{- if eq .Values.mode "managed" }}
      priorityClassName: system-cluster-critical
{{- end }}
{{ include "monitoring.affinity" . | indent 6 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      containers:
        - name: prometheus-operator
          image: {{ .Values.prometheusOperator.image.repository }}:{{ .Values.prometheusOperator.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.prometheusOperator.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          args:
            - --kubelet-service=kube-system/kubelet
            - --logtostderr=true
            - --log-level=debug
            - --namespaces={{ .Values.prometheusOperator.namespaces }}
            - --config-reloader-image={{ .Values.configmapReload.image.repository }}:{{ .Values.configmapReload.image.tag }}
            - --prometheus-config-reloader={{ .Values.prometheusConfigReloader.image.repository }}:{{ .Values.prometheusConfigReloader.image.tag }}
        - name: prometheus-operator-controller
          image: {{ .Values.prometheusOperatorController.image.repository }}:{{ .Values.prometheusOperatorController.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.prometheusOperatorController.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: INIT_IMAGE
              value: {{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
{{- end -}}
