{{- if and .Values.prometheus.enabled .Values.prometheus.ingress.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-ingress
{{- if or (eq .Values.mode "managed") .Values.prometheus.ingress.annotations }}
  annotations:
  {{- if eq .Values.mode "managed" }}
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/authz-type: "rbac"
    icp.management.ibm.com/secure-backends: "true"
    icp.management.ibm.com/secure-client-ca-secret: "{{ template "monitoring.fullname" . }}-client-certs"
    icp.management.ibm.com/rewrite-target: "/"
  {{- end }}
  {{- if .Values.alertmanager.ingress.annotations }}
{{ toYaml .Values.alertmanager.ingress.annotations | indent 4 }}
  {{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /prometheus
        backend:
          serviceName: {{ template "prometheus.fullname" . }}
          servicePort: {{ .Values.prometheus.port }}

{{- end -}}
