{{- if .Values.prometheus.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      protocol: TCP
    {{- if .Values.tls.enabled }}
      targetPort: 8443
    {{- else }}
      targetPort: 9090
    {{- end }}
  selector:
    prometheus: {{ template "prometheus.fullname" . }}
    component: prometheus
    release: {{ .Release.Name }}
  type: "{{ .Values.prometheus.service.type }}"
{{- end -}}