{{- if and (.Values.prometheus.enabled) (.Values.prometheus.alerts.elasticsearchClusterHealth) -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{.Chart.Version}}
    component: icp-prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: elasticsearch-cluster-health
spec:
  groups:
    - name: elasticsearchClusterHealth
      rules:
        - alert: elasticsearchClusterHealth
          expr: elasticsearch_cluster_health_up != 1
          for: 5m
          annotations:
            description: Elasticsearch cluster's health status is not green.
            summary: Elasticsearch cluster not healthy
{{- end -}}
