# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

# Default values for work-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

connectionManager: null

clusterName: null
clusterNamespace: null

clusterLabels: {}

deployedOnHub: false

userImpersonation: false

workManager:
  enabled: true

# klusterlet proxy related configuration
service:
  type: ClusterIP

ingress:
  type: None
  host: null
  port: null

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi


logLevel: 5

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    multicloud_manager: quay.io/open-cluster-management/multicloud-manager:3.2.0 