# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

replicas: 1

image: 
  repository: ibmcom/icp-cert-policy-controller
  tag: 4.1.0
  pullPolicy: IfNotPresent

args:
  frequency:
  verbosity: 0
  defaultDuration:

securityContext:
  pod:
    runAsUser: 10000
    runAsNonRoot: true    
  container:
    allowPrivilegeEscalation: false
    runAsUser: 10000
    readOnlyRootFilesystem: false
    runAsNonRoot: true

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists

podDnsPolicy: "ClusterFirstWithHostNet"
