# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "service-registry.fullname" . }}-coredns"
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ template "service-registry.name" . }}
    chart: {{ template "service-registry.chart" . }}
    component: mcm-svc-registry-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "service-registry.name" . }}
      release: {{ .Release.Name }}
      component: mcm-svc-registry-dns
  template:
    metadata:
      labels:
        app: {{ template "service-registry.name" . }}
        release: {{ .Release.Name }}
        component: mcm-svc-registry-dns
    spec:
      serviceAccountName: {{ template "service-registry.fullname" . }}
      containers:
      - name: mcm-svc-registry-dns
        image: "{{ .Values.coredns.image.repository }}:{{ .Values.coredns.image.tag }}"
        imagePullPolicy: {{ .Values.coredns.image.pullPolicy }}
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: "{{ template "service-registry.fullname" . }}-coredns"
            items:
            - key: Corefile
              path: Corefile
            - key: svcregistry.db
              path: svcregistry.db
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
