# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "service-registry.fullname" . }}-coredns"
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ template "service-registry.name" . }}
    chart: {{ template "service-registry.chart" . }}
    component: mcm-svc-registry-dns
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        reload
        cache 30
        file /etc/coredns/svcregistry.db {{ .Values.dnsSuffix }} {
          reload 5s
        }
    }
  svcregistry.db: |
    {{ .Values.dnsSuffix }}.    IN    SOA    mcm-svc-registry-dns.{{ .Release.Namespace }}.svc.cluster.local. hostmaster.cluster.local. {{ .Release.Time.Seconds }} 7200 1800 86400 30
{{- end }}
