# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-registry.fullname" . }}
  labels:
    app: {{ template "service-registry.name" . }}
    chart: {{ template "service-registry.chart" . }}
    component: "mcm-service-registry"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "service-registry.name" . }}
      component: "mcm-service-registry"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "service-registry.name" . }}
        component: "mcm-service-registry"
        controller: "operator"
        release: {{ .Release.Name }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ template "service-registry.fullname" . }}
      containers:
      - name: mcm-service-registry
        image: "{{ .Values.serviceRegistry.image.repository }}:{{ .Values.serviceRegistry.image.tag }}"
        imagePullPolicy: {{ .Values.serviceRegistry.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}  
        livenessProbe: null
        command: ["/mcm-service-registry-plugin"]
        args:
          - "--logtostderr=1"
          - "-v={{ .Values.logLevel }}"
          - "--dns-suffix={{ .Values.dnsSuffix }}"
          - "--dns-configmap={{ .Release.Namespace }}/{{ template "service-registry.fullname" . }}-coredns"
          - "--member-cluster-name={{ .Values.clusterName }}"
          - "--member-cluster-namespace={{ .Values.clusterNamespace }}"
          - "--hub-cluster-kubeconfig=/var/run/hub-kubeconfig/kubeconfig"
          - "--plugins={{ .Values.plugins }}"
        {{- if .Values.istioIngressGateway }}
          - "--istio-ingressgateway={{ .Values.istioIngressGateway }}"
        {{- end}}
        {{- if .Values.istioServiceEntryRegistryNamespace }}
          - "--istio-serviceentry-registry-namespace={{ .Values.istioServiceEntryRegistryNamespace }}"
        {{- end}}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/hub-kubeconfig
      volumes:
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.connectionManager }}-hub-kubeconfig
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
