# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{- if .Values.enabled }}
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: {{ template "work-manager.fullname" . }}
    app: {{ template "work-manager.name" . }}
    chart: {{ template "work-manager.chart" . }}
    release: {{ .Release.Name }}
    component: "work-manager"
    heritage: {{ .Release.Service }}
  name: {{ template "work-manager.fullname" . }}
spec:
  host: ""
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ template "work-manager.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
{{- end }}
