apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "search.fullname" . }}
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    component: "search"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
