# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ template "cisCrawler.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.cisCrawler.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "cisCrawler.fullname" . }}-config"
data:
        VAAAS_URL: "cos://{{ template "cisController.fullname" . }}-minio:9000/ciscos-host"
        MINIO_URL: "https://{{ template "cisController.fullname" . }}-minio:9000"
        FEATURES: "os,file,config,process"
        FREQUENCY: "86400"
        LOGLEVEL: "DEBUG"

        config_known_fpath: |-
                ### Host Config files
                /etc/login.defs
                /etc/pam.d/common-password
                /etc/login.def
                /etc/passwd
                /etc/group
                /etc/hosts
                /etc/hostname
                /etc/mtab
                /etc/fstab
                /etc/aliases

                ### AKS Config files
                /etc/kubernetes/azure.json
                /etc/kubernetes/certs/ca.crt

                ### AKS and GKE Config files
                /etc/systemd/system/kubelet.service
                /etc/default/kubelet
                /var/lib/kubelet/kubeconfig
                /var/lib/kubernetes/kubeconfig

                ### GKE Config files
                /etc/kubernetes/certs/ca.crt0
                /var/lib/kube-proxy/kubeconfig
                /etc/srv/kubernetes/pki/kubelet.crt

                ### OCP Master Config files
                /etc/origin/master/master-config.yaml
                /etc/origin/master/admin.kubeconfig
                /etc/origin/master/openshift-master.kubeconfig
                /etc/origin/node/pods/apiserver.yaml
                /etc/origin/node/pods/controller.yaml
                /etc/origin/node/pods/etcd.yaml
                /etc/etcd/etcd.conf
                /etc/etcd/peer.crt
                /etc/etcd/peer.key
                /etc/etcd/server.crt
                /etc/etcd/server.key
                /etc/origin/master/master.etcd-ca.crt
                /etc/origin/openvswitch
                /etc/cni/net.d
                /var/lib/etcd

                ### OCP Node Config files
                /etc/origin/node/node-config.yaml
                /etc/origin/node/node.kubeconfig
                /etc/systemd/system/atomic-openshift-node.service
                /etc/origin/node/client-ca.crt


                ### IKS Config files
                /etc/kubernetes/kubelet-kubeconfig
                /lib/systemd/system/kube-proxy.service
                /lib/systemd/system/kubelet.service
                /etc/kubernetes/kubelet-kubeconfig
                /etc/kubernetes/cert/kubelet.pem

                ### ICP Config files
                /etc/cfc/pods/master.json
                /etc/cfc/pods/etcd.json
                /etc/cfc/conf/admin.kubeconfig
                /etc/cfc/conf/admin.kubeconfig
                /etc/cfc/conf/kube-scheduler-config.yaml
                /etc/cfc/conf/kube-scheduler-config.yaml
                /etc/cfc/conf/kube-controller-manager-config.yaml
                /etc/cfc/conf/kube-controller-manager-config.yaml
                /etc/cfc/kubelet/kubelet-config
                /etc/cfc/kubelet/kubelet-service-config
                /etc/cfc/kubelet/kubelet-dynamic-config
                /etc/cfc/kube-proxy/config/kube-proxy-config.yaml
                /etc/cfc/kubelet
                /etc/kubernetes/admin.conf
