language: go

go:
  - "1.12.x"

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

stages:
  - build
  - publish

before_install:
  - git config --global url.git@github.com:open-cluster-management/.insteadOf https://github.com/open-cluster-management/
  - make init

  jobs:
  include:
    - stage: build
      name: "Build and push image"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/init
        - make check
        - make component/build
        - make component/push
        - echo "TRAVIS_EVENT_TYPE = $TRAVIS_EVENT_TYPE"

    - stage: publish
      name: "Publish Image"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
    #   after_script:
    #     - test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_TEST_RESULT" = "1" && ./build/slack-notification.sh || echo "Slack notification not sent"
