# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mcm-svc-registry-dns
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ template "service-registry.name" . }}
    release: {{ .Release.Name }}
    component: service-registry
spec:
  selector:
    app: {{ template "service-registry.name" . }}
    release: {{ .Release.Name }}
    component: service-registry
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
{{- end }}