# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
{{- if (not (.Values.deployedOnHub))}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "search.fullname" . }}-search-collector
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    component: "mcm-search"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    connectionManager: {{ .Values.connectionManager }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "search.name" . }}
      component: "mcm-search"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "search.name" . }}
        component: "mcm-search"
        controller: "operator"
        release: {{ .Release.Name }}
        chart: {{ template "search.chart" . }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: "IBM Multicloud Manager - Server"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.0"
    spec:
      containers:
      - name: collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.clusterName }}
        - name: CLUSTER_NAMESPACE
          value: {{ .Values.clusterNamespace }}
        - name: HUB_CONFIG
          value: /hubconfig/kubeconfig
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
        - name: hub-config
          mountPath: /hubconfig
        - name: helm-tiller-secret
          mountPath: /helmcerts
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .Values.connectionManager }}-hub-kubeconfig
      - name: helm-tiller-secret
        secret:
          secretName: {{ template "search.fullname" . }}-tiller-client-certs
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
{{- end }}
{{- end }}
