# Copyright Contributors to the Open Cluster Management project

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "search.fullname" . }}-pod
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    component: "search"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "search.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "search.fullname" . }}-pod
  apiGroup: rbac.authorization.k8s.io