# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "work-manager.fullname" . }}
  labels:
    app: {{ template "work-manager.name" . }}
    chart: {{ template "work-manager.chart" . }}
    component: "work-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    connectionManager: {{ .Values.connectionManager }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "work-manager.name" . }}
      component: "work-manager"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "work-manager.name" . }}
        component: "work-manager"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "work-manager.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.0"
    spec:
      serviceAccountName: {{ template "work-manager.fullname" . }}
      containers:
      {{- if .Values.workManager.enabled }}
      - name: work-manager
        image: "{{ .Values.workManager.image.repository }}:{{ .Values.workManager.image.tag }}"
        imagePullPolicy: {{ .Values.workManager.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        args:
          - "/klusterlet"
          - "--port=4443"
          - "--controller-config-file=/var/run/klusterlet/kubeconfig"
          - "--cluster-name={{ .Values.clusterName }}"
          - "--cluster-namespace={{ .Values.clusterNamespace }}"
          - "--cluster-labels={{ template "cluster-label.string" . }}"
        {{- if .Values.deployedOnHub }}
          - "--klusterlet-address={{ template "work-manager.fullname" . }}.{{ .Release.Namespace }}.svc"
        {{- else if eq .Values.service.type "LoadBalancer" }}
          - "--klusterlet-service={{ .Release.Namespace }}/{{ template "work-manager.fullname" . }}"
        {{- else if eq .Values.ingress.type "Ingress" }}
          - "--klusterlet-ingress={{ .Release.Namespace }}/{{ template "work-manager.fullname" . }}"
        {{- if .Values.ingress.host }}
          - "--klusterlet-address={{ .Values.ingress.host }}"
        {{- else }}
          - "--klusterlet-address={{ .Values.clusterName }}.klusterlet.mcm"
        {{- end }}
        {{- if .Values.ingress.port }}
          - "--klusterlet-port={{ .Values.ingress.port }}"
        {{- end }}
        {{- else if eq .Values.ingress.type "Route" }}
          - "--klusterlet-route={{ .Release.Namespace }}/{{ template "work-manager.fullname" . }}"
        {{- if .Values.ingress.host }}
          - "--klusterlet-address={{ .Values.ingress.host }}"
        {{- end }}
        {{- if .Values.ingress.port }}
          - "--klusterlet-port={{ .Values.ingress.port }}"
        {{- end }}
        {{- end }}
        {{- if .Values.prometheusIntegration.enabled }}
        {{- if .Values.prometheusIntegration.scrapeTarget }}
          - "--prometheus-scrape-target={{ .Values.prometheusIntegration.scrapeTarget }}"
        {{- end }}
        {{- if .Values.prometheusIntegration.service }}
          - "--prometheus-service={{ .Values.prometheusIntegration.service }}"
        {{- end }}
        {{- if .Values.prometheusIntegration.secret }}
          - "--prometheus-secret={{ .Values.prometheusIntegration.secret }}"
        {{- end }}
        {{- if .Values.prometheusIntegration.useBearerToken }}
          - "--prometheus-use-bearer-token={{ .Values.prometheusIntegration.useBearerToken }}"
        {{- end }}
        {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.connectionManager }}-hub-kubeconfig
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
