# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "application-manager.fullname" . }}
  labels:
    app: {{ template "application-manager.name" . }}
    chart: {{ template "application-manager.chart" . }}
    component: "application-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    connectionManager: {{ .Values.connectionManager }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "application-manager.name" . }}
      component: "application-manager"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "application-manager.name" . }}
        component: "application-manager"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "application-manager.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.1"
    spec:
      hostAliases:
      - hostnames:
        - {{ .Values.helmcrd.hostname }}
        ip: {{ .Values.helmcrd.ip }}
      serviceAccountName: {{ template "application-manager.fullname" . }}
      containers:
      - name: deployable-controller
        image: "{{ .Values.deployable.image.repository }}:{{ .Values.deployable.image.tag }}"
        imagePullPolicy: "{{ .Values.deployable.image.pullPolicy }}"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        command: ["./manager"]
        args:
          - "--alsologtostderr"
          - "--managed-cluster-name={{ .Values.clusterName }}"
          - "--managed-cluster-namespace={{ .Values.clusterNamespace }}"
          - "--remote-cluster-configfile=/var/run/klusterlet/kubeconfig"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      - name: subscription-controller
        image: "{{ .Values.subscription.image.repository }}:{{ .Values.subscription.image.tag }}"
        imagePullPolicy: "{{ .Values.subscription.image.pullPolicy }}"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        command: ["./manager"]
        args:
          - "--alsologtostderr"
          - "--managed-cluster-name={{ .Values.clusterName }}"
          - "--managed-cluster-namespace={{ .Values.clusterNamespace }}"
          - "--remote-cluster-configfile=/var/run/klusterlet/kubeconfig"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      - name: helm-crd-controller
        image: "{{ .Values.helmcrd.image.repository }}:{{ .Values.helmcrd.image.tag }}"
        imagePullPolicy: "{{ .Values.helmcrd.image.pullPolicy }}"
        securityContext:
          procMount: Default
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        command:
          - /controller
        args:
          - --home=/helm
          - "--host={{ .Values.tillerIntegration.endpoint }}"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
          - name: home
            mountPath: /helm
          - name: helm-crd-controller-tiller-client-certs
            mountPath: /helmcerts
        env:
          - name: HELM_TLS_CA_CERT
            value: "/helmcerts/ca.crt"
          - name: HELM_TLS_CERT
            value: "/helmcerts/tls.crt"
          - name: HELM_TLS_KEY
            value: "/helmcerts/tls.key"
          - name: HELM_TLS_VERIFY
            value: "1"
          - name: HELM_TLS_ENABLE
            value: "1"
          - name: TMPDIR
            value: "/helm"
      - name: helm-crd-admission-controller
        image: "{{ .Values.helmcrd_admission_controller.image.repository }}:{{ .Values.helmcrd_admission_controller.image.tag }}"
        imagePullPolicy: "{{ .Values.helmcrd_admission_controller.image.pullPolicy }}"
        args:
          - -tlsCertFile=/webhookcerts/tls.crt
          - -tlsKeyFile=/webhookcerts/tls.key
          - -alsologtostderr
          - -v=4
          - 2>&1
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
          - name: helm-crd-admission-controller-certs
            mountPath: /webhookcerts
            readOnly: true
        env:
          - name: SERVICE_ACCOUNT_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.connectionManager }}-hub-kubeconfig
        - name: helm-crd-controller-tiller-client-certs
          secret:
            secretName: {{ template "application-manager.fullname" . }}-tiller-client-certs
            defaultMode: 420
        - name: helm-crd-admission-controller-certs
          secret:
            secretName: helm-crd-admission-controller-certs
        - name: home
          emptyDir: {}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
