# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{ if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "topology.fullname" . }}-weave-scope
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjAiLCBHaXRDb21taXQ6ImZjMzJkMmYzNjk4ZTM2YjkzMzIyYTM0NjVmNjNhMTRlOWYwZWFlYWQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTAzLTI3VDAwOjEzOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjkuNCIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJkYXJ3aW4vYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwIiwgR2l0VmVyc2lvbjoidjEuMTAuMCtpY3AtZWUiLCBHaXRDb21taXQ6IjljYjY0ZGU0Y2E0ZDAzOWMzNWY0YTI5NzIxYWE1Y2Y3ODc2NDhhMTUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTA0LTI3VDA2OjMyOjE4WiIsIEdvVmVyc2lvbjoiZ28xLjkuMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==",
          "date": "Tue May 08 2018 17:14:07 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    app: {{ template "topology.name" . }}
    chart: {{ template "topology.chart" . }}
    component: "weave-scope-app"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: {{ template "topology.name" . }}
    component: "weave-scope-app"
    release: {{ .Release.Name }}
{{ end }}
