apiVersion: v1
appVersion: 0.7.0.1
description: Service for issuing and managing certificates on IBM Cloud Private.
keywords:
- amd64
- ppc64le
- s390x
- OpenSource
- ICP
- IcpClusterResource
- Security
- cert-manager
- kube-lego
- letsencrypt
- tls
- Development
- IBM Cloud Private
kubeVersion: '>=1.9.0'
name: ibm-cert-manager
tillerVersion: '>=2.7.0'
version: 0.7.1
