# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

# requirements.yaml
dependencies:
- name: ibm-cert-manager-crd
  version: "0.7.1"
  repository: "file://ibm-cert-manager-crd"
  condition: policy-controller.enabled
- name: ibm-cert-policy-controller
  version: "0.0.1"
  repository: "file://ibm-cert-policy-controller"
  condition: policy-controller.enabled
