# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: service-registry
version: 3.2.0 #need to update completely for 3.2.1 :)
