# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "connection-manager.fullname" . }}
  labels:
    app: {{ template "connection-manager.name" . }}
    chart: {{ template "connection-manager.chart" . }}
    component: "connection-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "connection-manager.name" . }}
      component: "connection-manager"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "connection-manager.name" . }}
        component: "connection-manager"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "connection-manager.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.0"
    spec:
      serviceAccountName: {{ template "connection-manager.fullname" . }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "/klusterlet-operator"
          - "--operator-configmap={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}"
          - "--cert-store-secret={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}-cert-store"
          - "--cluster={{ .Values.clusterNamespace }}/{{ .Values.clusterName }}"
          - "--klusterlet-secret={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}-hub-kubeconfig"
          - "--klusterlet-labels=controller=operator,release={{ template "connection-manager.fullname" . }}" 
          {{- if gt .Values.replicas 1.0 }}
          - "--leader-elect=true"
          {{- end }}
        livenessProbe: null
        readinessProbe: null
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}

