# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

description: IBM monitoring service in private cloud
engine: gotpl
keywords:
- IcpClusterResource
- ICP
- amd64
- ppc64le
- s390x
- OpenSource
- DevOps
kubeVersion: '>=1.9.0-0'
name: ibm-icpmonitoring
sources:
- https://github.com/prometheus/prometheus
- https://github.com/prometheus/alertmanager
- https://github.com/prometheus/node_exporter
- https://github.com/kubernetes/kube-state-metrics
- https://github.com/grafana/grafana
- https://github.com/prometheus/collectd_exporter
- https://github.com/justwatchcom/elasticsearch_exporter
tillerVersion: '>=2.7.0'
version: 1.6.0
