# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

mode: managed
standalone: true
environment: non-openshift
tls:
  enabled: true
  issuer: icp-ca-issuer
  issuerKind: ClusterIssuer
  sslCiphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
  ca:
    secretName: cluster-ca-cert
    certFieldName: tls.crt
  server:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
  exporter:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
  client:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
imagePullPolicy: IfNotPresent
imagePullSecrets: ""
clusterAddress: 127.0.0.1
clusterPort: 8443
clusterDomain: cluster.local
clusterName: mycluster
crdCreation: false

prometheus:
  enabled: true
  image:
    repository: ibmcom/prometheus
    tag: v2.8.0-f1
  port: 9090
  scrapeInterval: 1m
  evaluationInterval: 1m
  retention: 24h
  args: {}
  persistentVolume:
    enabled: false
    useDynamicProvisioning: true
    size: 10Gi
    storageClass: ""
    existingClaimName: ""
    selector:
      label: ""
      value: ""
  probe:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configFiles: prometheusConfig
  ## if true, will create rbac role and related rolebinding for k8s resource access
  ##
  rbacRoleCreation: true
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP
  etcdTarget:
    enabled: true
    etcdAddress: ["127.0.0.1"]
    etcdPort: "4001"
    secret: etcd-secret
    tlsConfig: {}
  alerts:
    nodeMemoryUsage:
      enabled: true
      nodeMemoryUsageThreshold: 85
    highCPUUsage:
      enabled: true
      highCPUUsageThreshold: 85
    failedJobs: true
    elasticsearchClusterHealth: false
    podsTerminated: true
    podsRestarting: true

alertmanager:
  enabled: true
  image:
    repository: ibmcom/alertmanager
    tag: v0.15.0-f4
  port: 9093
  persistentVolume:
    enabled: false
    useDynamicProvisioning: true
    size: 1Gi
    storageClass: ""
    existingClaimName: ""
    selector:
      label: ""
      value: ""
  probe:
    enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  configFiles: alermanagerConfig
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi
  image:
    repository: ibmcom/kube-state-metrics
    tag: v1.3.0-f4
  port: 80
  probe:
    enabled: true

nodeExporter:
  enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi
  image:
    repository: ibmcom/node-exporter
    tag: v0.16.0-f4
  port: 8445
  healthyPort: 8446
  listenPort: 9100
  probe:
    enabled: true

grafana:
  enabled: true
  image:
    repository: "ibmcom/grafana"
    tag: "5.2.0-f4"
  port: 3000
  persistentVolume:
    enabled: false
    useDynamicProvisioning: true
    size: 1Gi
    storageClass: ""
    existingClaimName: ""
    selector:
      label: ""
      value: ""
  probe:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configFiles: grafanaConfig
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP
  elasticsearchDash:
    enabled: true

collectdExporter:
  enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi
  image:
    repository: ibmcom/collectd-exporter
    tag: v0.4.0-f4
  service:
    serviceMetricsPort: 9103
    serviceCollectorPort: 25826
  probe:
    enabled: true

configmapReload:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi
  image:
    repository: ibmcom/configmap-reload
    tag: v0.2.2-f4

router:
  image:
    repository: ibmcom/icp-management-ingress
    tag: latest
  subjectAlt: 127.0.0.1
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi

elasticsearchExporter:
  enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi
  image:
    repository: ibmcom/elasticsearch-exporter
    tag: 1.0.2-f4
  esUri: https://elasticsearch:9200
  tls:
    enabled: true
    ca:
      secretName: cluster-ca-cert
      certFieldName: tls.crt
    client:
      existingSecretName: ""
      certFieldName: tls.crt
      keyFieldName: tls.key
  port: 9108
  probe:
    enabled: true

dashboardController:
  image:
    repository: ibmcom/dashboard-controller
    tag: v1.1.0-f1
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi

alertruleController:
  image:
    repository: ibmcom/alert-rule-controller
    tag: v1.1.0-f1
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi

prometheusOperator:
  image:
    repository: ibmcom/prometheus-operator
    tag: v0.31
  namespaces: ""
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi

prometheusOperatorController:
  image:
    repository: ibmcom/prometheus-operator-controller
    tag: v1.0.0
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 64Mi

prometheusConfigReloader:
  image:
    repository: ibmcom/prometheus-config-reloader
    tag: v0.31

curl:
  image:
    repository: ibmcom/curl
    tag: 4.2.0-f4

init:
  image:
    repository: ibmcom/icp-initcontainer
    tag: 1.0.0-f4
