# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019. All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by
# GSA ADP Schedule Contract with IBM Corp.
#
{{- if .Values.clusterRoleEnabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "metering.fullname" . }}
  labels:
    app: {{ template "metering.name" . }}
    chart: {{ template "metering.chart" . }}
    component: "metering"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "metering.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "metering.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}
