{{- if .Values.api.enabled }}
{{- if .Values.reader.enabled }}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
#
#  This service definition exposes the API server as a loadbalanced service named "metering-server"
#  in K8s so that it can be accessed as http://metering-server:4000/api/v1 in K8s.
#
# swagger documentation for the api is at the https://metering-server:4000/api/swagger endpoint
#

apiVersion: v1
kind: Service
metadata:
  name: metering-server
  labels:
    app.kubernetes.io/name: metering-server
    app.kubernetes.io/component: meteringsvc
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: "{{ .Release.Name }}"

spec:
  type: ClusterIP
  ports:
    - name: apiserver
      port: 4000
      targetPort: 4000

  selector:
    app: metering-reader
    component: meteringsvc

{{- end }}
{{- end }}