# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: agent.open-cluster-management.io/v1beta1
kind: CertManager
metadata:
  name: cert-manager
spec:
  fullnameOverride: klusterlet-certmgr
  hostNetwork: false
  serviceAccount:
    create: true
    name: null
  clusterResourceNamespace: klusterlet
  image:
    repository: ibmcom/icp-cert-manager-controller
    tag: 0.7.0.1
    pullPolicy: IfNotPresent
  policy-controller:
    enabled: false
