apiVersion: klusterlet.mcm.ibm.com/v1alpha1
kind: Tiller
metadata:
  name: klusterlet-tiller
spec:
  fullNameOverride: "klusterlet-tiller"
  caCertIssuer: "klusterlet-self-signed"
  tiller_default_admin_user: "klusterlet-admin"
