apiVersion: klusterlet.mcm.ibm.com/v1alpha1
kind: ConnectionManager
metadata:
  name: connection-manager
spec:
  clusterName: hao-dev-cluster
  clusterNamespace: hao-dev-cluster
  
  bootstrapConfig:
    hub0:
      name: hub0
      secret: kube-system/klusterlet-bootstrap
    hub1:
      name: null
      secret: null
