# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: multicloud.ibm.com/v1beta1
kind: Tiller
metadata:
  name: endpoint-tiller
spec:
  fullNameOverride: "endpoint-tiller"
  caCertIssuer: "endpoint-self-signed"
  tiller_default_admin_user: "endpoint-admin"
  kubernetes_cluster_type: "noticp" 
  random_ip_enabled: false
  tiller_service_ip: 0.0.0.0