apiVersion: klusterlet.mcm.ibm.com/v1alpha1
kind: PolicyController
metadata:
  name: policy-controller
spec:
  connectionManager: CONNECTION_MANAGER_RELEASE
  clusterName: CLUSTER_NAME
  clusterNamespace: CLUSTER_NAMESPACE
