# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: klusterlet.mcm.ibm.com/v1alpha1
kind: ServiceRegistry
metadata:
  name: service-registry
spec:
  enabled: true

  serviceRegistry:
    image:
      repository: ibmcom/mcm-service-registry
      tag: 3.2.0
      pullPolicy: IfNotPresent

  coredns:
    image:
      repository: ibmcom/coredns
      tag: 1.2.6.1
      pullPolicy: IfNotPresent
    dnsSuffix: "mcm.svc"
    plugins: "kube-service"
    clusterProxyIP: ""
