# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: agent.open-cluster-management.io/v1alpha1
kind: WorkManager
metadata:
  name: work-manager
spec:
  connectionManager: CONNECTION_MANAGER_RELEASE

  clusterName: CLUSTER_NAME
  clusterNamespace: CLUSTER_NAMESPACE

  clusterLabels:
    cloud: "IBM"
    vendor: "ICP"
    environment: "Dev"
    region: "US"
    datacenter: "toronto"
    owner: "marketing"

  # ICP
  # service:
  #   type: ClusterIP
  # ingress:
  #   type: Ingress
  #   host: null #required
  #   port: null #required

  # OpenShift
  service:
    type: ClusterIP
  ingress:
    type: Route
    host: null
    port: null

  # AKS EKS GKE IKS
  # service:
  #   type: LoadBalancer
  #
  # ingress:
  #   type: None
  #   host: null
  #   port: null

