apiVersion: klusterlet.mcm.ibm.com/v1alpha1
kind: WorkManager
metadata:
  name: work-manager
spec:
  connectionManager: CONNECTION_MANAGER_RELEASE
  tiller: TILLER_RELEASE

  clusterName: CLUSTER_NAME
  clusterNamespace: CLUSTER_NAMESPACE

  clusterLabels:
    cloud: "IBM"
    vendor: "ICP"
    environment: "Dev"
    region: "US"
    datacenter: "toronto"
    owner: "marketing"

  tillerIntegration:
    enabled: true
    endpoint: TILLER_RELEASE:44134
    certIssuer: TILLER_RELEASE
    helmReleasePrefix: "md"
    autoGenSecret: true
    user: admin

  # ICP 
  # service:
  #   type: ClusterIP
  # ingress:
  #   type: Ingress
  #   host: null #required
  #   port: null #required

  # OpenShift
  service:
    type: ClusterIP
  ingress:
    type: Route
    host: null
    port: null

  # AKS EKS GKE IKS
  # service:
  #   type: LoadBalancer
  #
  # ingress:
  #   type: None
  #   host: null
  #   port: null

  # OpenShift monitoring
  prometheusIntegration:
    enabled: true
    service: "openshift-monitoring/prometheus-k8s"
    secret: "kube-system/monitoring-monitoring-client-certs"
    useBearerToken: true

  # ICP monitoring
  # prometheusIntegration:
  #   enabled: true
  #   service: "kube-system/monitoring-prometheus"
  #   secret: "kube-system/monitoring-monitoring-client-certs"
  #   useBearerToken: false
