apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: searches.klusterlet.mcm.ibm.com
spec:
  group: klusterlet.mcm.ibm.com
  names:
    kind: SearchCollector
    listKind: SearchCollectorList
    plural: searchcollectors
    singular: searchcollector
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
