# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: multicloud.ibm.com/v1beta1
kind: Metering
metadata:
  name: klusterlet-metering-cr
spec:
  fullnameOverride: klusterlet-metering

  api:
    enabled: false

  ui:
    enabled: false

  mcmui:
    enabled: false

  dm:
    enabled: true
    image:
      repository: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/metering-data-manager-amd64
      pullPolicy: Always
    # nodeSelector is used when the chart is deployed in an ICP environment
    nodeSelectorEnabled: false
    # priorityClassName is used when the chart is deployed in an ICP environment
    priorityClassNameEnabled: false

  reader:
    enabled: true
    image:
      repository: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/metering-data-manager-amd64
      pullPolicy: Always

  sender:
    enabled: true
    clusterName: steve
    clusterNamespace: steve
    hubKubeConfigSecret: klusterlet-connmgr-hub-kubeconfig 
    image:
      repository: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/metering-data-manager-amd64
      pullPolicy: Always
    # nodeSelector is used when the chart is deployed in an ICP environment
    nodeSelectorEnabled: false

  imagePullSecrets:
    - metering-collector-pull

  # serviceAccount is used when the chart is deployed by an operator in a non-ICP environment
  serviceAccountNameEnabled: true

  # clusterRole is used when the chart is deployed by an operator in a non-ICP environment
  clusterRoleEnabled: true

  mongo:
    clustercertssecret: klusterlet-mongo-ca-cert
    clientcertssecret: klusterlet-mongo-client-cert
    username:
      secret: klusterlet-mongo-admin
    password:
      secret: klusterlet-mongo-admin
