# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.bitnami.com
spec:
  group: helm.bitnami.com
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  version: v1
