# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "minio.fullname" . }}-config
  labels:
    app: {{ include "minio.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  config.json: |
    {
        "version":"32",
        "browser":"on",
        "domain":"",
        "storageclass":{
            "standard":"",
            "rrs":""
        },
        "cache":{
            "drives":[
            ],
            "expiry":90,
            "exclude":[
            ]
        },
        "notify":{
            "amqp":{
                "1":{
                    "enable":false,
                    "url":"",
                    "exchange":"",
                    "routingKey":"",
                    "exchangeType":"",
                    "deliveryMode":0,
                    "mandatory":false,
                    "immediate":false,
                    "durable":false,
                    "internal":false,
                    "noWait":false,
                    "autoDeleted":false
                }
            },
            "elasticsearch":{
                "1":{
                    "enable":false,
                    "format":"",
                    "url":"",
                    "index":""
                }
            },
            "kafka":{
                "1":{
                    "enable":false,
                    "brokers":[
                        ""
                    ],
                    "topic":"vacos-notifications"
                },
                "2":{
                    "enable":false,
                    "brokers":[
                        ""
                    ],
                    "topic":"vacos-hf-notifications"
                }
            },
            "mqtt":{
                "1":{
                    "enable":false,
                    "broker":"",
                    "topic":"",
                    "qos":0,
                    "clientId":"",
                    "username":"",
                    "password":"",
                    "reconnectInterval":0,
                    "keepAliveInterval":0
                }
            },
            "mysql":{
                "1":{
                    "enable":false,
                    "format":"",
                    "dsnString":"",
                    "table":"",
                    "host":"",
                    "port":"",
                    "user":"",
                    "password":"",
                    "database":""
                }
            },
            "nats":{
                "1":{
                    "enable":false,
                    "address":"",
                    "subject":"",
                    "username":"",
                    "password":"",
                    "token":"",
                    "secure":false,
                    "pingInterval":0,
                    "streaming":{
                        "enable":false,
                        "clusterID":"",
                        "clientID":"",
                        "async":false,
                        "maxPubAcksInflight":0
                    }
                }
            },
            "postgresql":{
                "1":{
                    "enable":false,
                    "format":"",
                    "connectionString":"",
                    "table":"",
                    "host":"",
                    "port":"",
                    "user":"",
                    "password":"",
                    "database":""
                }
            },
            "redis":{
                "1":{
                    "enable":false,
                    "format":"",
                    "address":"",
                    "password":"",
                    "key":""
                }
            },
            "webhook":{
                "1":{
                    "enable":false,
                    "endpoint":""
                }
            }
        }
    }