# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ include "minio.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  ports:
  - name: minio-port
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: {{ include "minio.name" . | quote }}
    release: {{ .Release.Name | quote }}

