# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-component-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: endpoint-component-operator
  template:
    metadata:
      labels:
        name: endpoint-component-operator
    spec:
      serviceAccountName: endpoint-component-operator
      containers:
        - name: endpoint-component-operator
          # Replace this with the built image name
          image: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/endpoint-component-operator:liuhao
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "endpoint-component-operator"
