# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: klusterlet-addon-operator
rules:
- apiGroups:
  - '*'
  # attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
# - apiGroups: null
#   attributeRestrictions: null
#   nonResourceURLs:
#   - '*'
#   resources: []
#   verbs:
#   - '*'
