{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: metering-receiver
  labels:
    app: metering-dm
    component: meteringsvc
    app.kubernetes.io/name: metering-dm
    app.kubernetes.io/component: meteringsvc
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"

spec:
  ports:
    - name: metering-receiver
      port: 5000
  selector:
    app: metering-dm
    component: meteringsvc
{{- end }}