{{- if .Values.api.enabled }}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
kind: Service
metadata:
  name: metering-receiver
  labels:
    app: metering-dm
    component: meteringsvc
    app.kubernetes.io/name: metering-dm
    app.kubernetes.io/component: meteringsvc
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"

spec:
  ports:
    - name: metering-receiver
      port: 5000
  selector:
    app: metering-dm
    component: meteringsvc
{{- end }}