# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.mcmui.enabled }}
#
#  This service definition exposes the UI server pod as a loadbalanced service named "metering-ui"
#  in K8s
#
#  The full URL for accessing the UI looks something like the following where the IP addr and
#  port need to be adjusted for the particular cluster and service name defined for the UI server:
#    https://<cluster-ip>:8443/metering/dashboard?dashboard=cpi.icp.main
#
apiVersion: v1
kind: Service
metadata:
  name: metering-mcmui
  labels:
    app: metering-mcmui
    component: meteringsvc
    app.kubernetes.io/name: metering-mcmui
    app.kubernetes.io/component: meteringsvc
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: ClusterIP
  ports:
    - name: metering-mcm-dashboard
      port: 3001
      targetPort: 3001
  selector:
    app: metering-mcmui
    component: meteringsvc
{{- end }}