# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

#  This service definition exposes the DM server pod as a loadbalanced service named "metering-dm"
#  in K8s
{{- if .Values.dm.enabled }}
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/scheme: 'http'
  name: metering-dm
  labels:
    app.kubernetes.io/name: metering-dm
    app.kubernetes.io/component: meteringsvc
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"

spec:
  ports:
    - name: datamanager
      port: 3000
  selector:
    app: metering-dm
    component: meteringsvc
{{- end }}
{{- end }}