{{- if and (.Values.auth.enabled) (not .Values.auth.existingAdminSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if not .Values.auth.adminPassword }}
  annotations:
    "helm.sh/hook": pre-install
{{- end }}
  name: {{ template "mongodb-replicaset.adminSecret" . }}
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: "{{ b64enc (include "mongodb-replicaset.adminPassword" .) }}"
{{- end -}}
