apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb-replicaset.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "mongodb-replicaset.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "mongodb-replicaset.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "mongodb-replicaset.name" . }}
        release: {{ .Release.Name }}
      annotations:
      {{- if and (.Values.metrics.prometheusServiceDiscovery) (.Values.metrics.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
      {{- end }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
{{- if .Values.priorityClassNameEnabled }}
      priorityClassName: system-cluster-critical
{{- end }}
{{- if .Values.serviceAccountNameEnabled }}
      serviceAccountName: {{ template "mongodb-replicaset.fullname" . }}
{{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        - name: install
          image: "{{ .Values.installImage.repository }}:{{ .Values.installImage.tag }}"
          command:
            - /install/install.sh
          args:
            - --work-dir=/work-dir
            - --config-dir=data/configdb
          imagePullPolicy: "{{ .Values.installImage.pullPolicy }}"
          volumeMounts:
            - name: mongodbdir
              subPath: workdir
              mountPath: /work-dir
            - name: configdir
              mountPath: /data/configdb
            - name: config
              mountPath: /configdb-readonly
            - name: install
              mountPath: /install
          {{- if .Values.auth.enabled }}
            - name: keydir
              mountPath: /keydir-readonly
          {{- end }}
          {{- if .Values.tls.enabled }}
            - name: ca
              mountPath: /ca-readonly
          {{- end }}
            - name: mongodbdir
              subPath: datadir
              mountPath: /data/db
        - name: bootstrap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /work-dir/peer-finder
          args:
            - -on-start=/init/on-start.sh
            - "-service={{ template "mongodb-replicaset.fullname" . }}"
          {{- if .Values.clusterDomain }}
            - -domain={{ .Values.clusterDomain }}
          {{- end }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.securityContext.enabled }}
          securityContext:
{{ toYaml .Values.securityContext.values | indent 12 }}
        {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: REPLICA_SET
              value: {{ .Values.replicaSet }}
          {{- if .Values.auth.enabled }}
            - name: AUTH
              value: "true"
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.adminSecret" . }}"
                  key: user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.adminSecret" . }}"
                  key: password
          {{- if .Values.metrics.enabled }}
            - name: METRICS
              value: "true"
            - name: METRICS_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.metricsSecret" . }}"
                  key: user
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.metricsSecret" . }}"
                  key: password
          {{- end }}
          {{- end }}
          {{- if .Values.network_ip_version }}
            - name: NETWORK_IP_VERSION
              value: {{ .Values.network_ip_version }}
          {{- end }}
          volumeMounts:
            - name: mongodbdir
              subPath: workdir
              mountPath: /work-dir
            - name: configdir
              mountPath: /data/configdb
            - name: init
              mountPath: /init
            - name: mongodbdir
              subPath: datadir
              mountPath: /data/db
      containers:
        - name: {{ template "mongodb-replicaset.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.securityContext.enabled }}
          securityContext:
{{ toYaml .Values.securityContext.values | indent 12 }}
        {{- end }}
          ports:
            - name: peer
              containerPort: {{ .Values.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          command:
            - mongod
            - --config=/data/configdb/mongod.conf
          {{- if .Values.auth.enabled }}
          env:
            - name: AUTH
              value: "true"
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.adminSecret" . }}"
                  key: user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.adminSecret" . }}"
                  key: password
          {{- end }}
          livenessProbe:
            exec:
              command:
                - mongo
              {{- if and (.Values.tls.enabled) }}
                - --ssl
                - --sslCAFile=/data/configdb/tls.crt
                - --sslPEMKeyFile=/work-dir/mongo.pem
              {{- end }}
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          readinessProbe:
            exec:
              command:
                - mongo
              {{- if and (.Values.tls.enabled) }}
                - --ssl
                - --sslCAFile=/data/configdb/tls.crt
                - --sslPEMKeyFile=/work-dir/mongo.pem
              {{- end }}
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          volumeMounts:
            - name: mongodbdir
              subPath: datadir
              mountPath: /data/db
            - name: configdir
              mountPath: /data/configdb
            - name: mongodbdir
              subPath: workdir
              mountPath: /work-dir
    {{ if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        {{- if .Values.securityContext.enabled }}
          securityContext:
{{ toYaml .Values.securityContext.values | indent 12 }}
        {{- end }}
          command:
            - sh
            - -ec
            - >-
              /bin/mongodb_exporter
            {{- if .Values.auth.enabled }}
              --mongodb.uri mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:{{ .Values.port }}
            {{- else }}
              --mongodb.uri mongodb://localhost:{{ .Values.port }}
            {{- end }}
            {{- if .Values.tls.enabled }}
              --mongodb.tls
              --mongodb.tls-ca=/data/configdb/tls.crt
              --mongodb.tls-cert=/work-dir/mongo.pem
            {{- end }}
              --mongodb.socket-timeout={{ .Values.metrics.socketTimeout }}
              --mongodb.sync-timeout={{ .Values.metrics.syncTimeout }}
              --web.telemetry-path={{ .Values.metrics.path }}
              --web.listen-address=:{{ .Values.metrics.port }}
          volumeMounts:
            - name: configdir
              mountPath: /data/configdb
            - name: mongodbdir
              subPath: workdir
              mountPath: /work-dir
          env:
          {{- if .Values.auth.enabled }}
            - name: METRICS_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.metricsSecret" . }}"
                  key: user
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "mongodb-replicaset.metricsSecret" . }}"
                  key: password
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port  }}
          resources:
{{ toYaml .Values.metrics.resources | indent 12 }}
          livenessProbe:
            exec:
              command:
                - sh
                - -ec
                - >-
                  /bin/mongodb_exporter
                {{- if .Values.auth.enabled }}
                  --mongodb.uri mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:{{ .Values.port }}
                {{- else }}
                  --mongodb.uri mongodb://localhost:{{ .Values.port }}
                {{- end }}
                {{- if .Values.tls.enabled }}
                  --mongodb.tls
                  --mongodb.tls-ca=/data/configdb/tls.crt
                  --mongodb.tls-cert=/work-dir/mongo.pem
                {{- end }}
                  --test
            initialDelaySeconds: 30
            periodSeconds: 10
    {{ end }}

    {{- if .Values.nodeSelectorEnabled }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "mongodb-replicaset.fullname" . }}
        - name: init
          configMap:
            defaultMode: 0755
            name: {{ template "mongodb-replicaset.fullname" . }}-init
        - name: install
          configMap:
            defaultMode: 0755
            name: {{ template "mongodb-replicaset.fullname" . }}-install
        {{- if .Values.tls.enabled }}
        - name: ca
          secret:
            defaultMode: 0400
            secretName: {{ template "mongodb-replicaset.casecret" . }}
        {{- end }}
        {{- if .Values.auth.enabled }}
        - name: keydir
          secret:
            defaultMode: 0400
            secretName: {{ template "mongodb-replicaset.keySecret" . }}
        {{- end }}
        - name: configdir
          emptyDir: {}

{{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mongodbdir
        annotations:
        {{- range $key, $value := .Values.persistentVolume.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistentVolume.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistentVolume.size | quote }}
      {{- if .Values.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.persistentVolume.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistentVolume.storageClass }}"
      {{- end }}
      {{- end }}
{{- else }}
        - name: mongodbdir
          emptyDir: {}
{{- end }}
