{{- if and (.Values.auth.enabled) (not .Values.auth.existingAdminSecret) -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if not .Values.auth.adminPassword }}
  annotations:
    "helm.sh/hook": pre-install
{{- end }}
  name: {{ template "mongodb-replicaset.adminSecret" . }}
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: "{{ b64enc (include "mongodb-replicaset.adminPassword" .) }}"
{{- end -}}
