{{- if and (.Values.tls.enabled)  (not .Values.tls.casecret) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb-replicaset.fullname" . }}-ca
data:
  tls.key: {{ .Values.tls.cakey }}
  tls.crt: {{ .Values.tls.cacert }}
{{- end -}}
