apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "connection-manager.fullname" . }}
  labels:
    app: {{ template "connection-manager.name" . }}
    chart: {{ template "connection-manager.chart" . }}
    component: "connection-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
