kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "work-manager.fullname" . }}
  labels:
    app: {{ template "work-manager.name" . }}
    chart: {{ template "work-manager.chart" . }}
    component: "work-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "work-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
