{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "work-manager.fullname" . }}
  labels:
    app: {{ template "work-manager.name" . }}
    chart: {{ template "work-manager.chart" . }}
    component: "work-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "work-manager.name" . }}
      component: "work-manager"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "work-manager.name" . }}
        component: "work-manager"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "work-manager.chart" . }}
    spec:
      serviceAccountName: {{ template "work-manager.fullname" . }}
      containers:
      {{- if .Values.workManager.enabled }}
      - name: lease-controller
        image: "{{ .Values.global.imageOverrides.klusterlet_addon_lease_controller }}"
        command:
        - klusterlet-addon-lease-controller
        args:
        - -lease-name
        - {{ .Values.leaseController.name }}
        - -lease-namespace
        - {{ .Values.clusterNamespace }}
        - -hub-kubeconfig-secret
        - {{ .Values.hubKubeconfigSecret }}
        - -lease-duration
        - "60"
        - -startup-delay
        - "10"
        resources:
{{ toYaml .Values.leaseController.resources | indent 10 }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      - name: acm-agent
        image: "{{ .Values.global.imageOverrides.multicloud_manager }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        args:
          - "/agent"
          - "--port=4443"
          - "--hub-kubeconfig=/var/run/klusterlet/kubeconfig"
          - "--cluster-name={{ .Values.clusterName }}"
        {{- if (or (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1/MultiClusterHub") (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1beta1/MultiClusterHub")) }}
          - "--agent-address={{ template "work-manager.fullname" . }}.{{ .Release.Namespace }}.svc"
          - "--agent-port=443"
        {{- else if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
          - "--agent-route={{ .Release.Namespace }}/{{ template "work-manager.fullname" . }}"
        {{- else if eq .Values.service.type "LoadBalancer" }}
          - "--agent-service={{ .Release.Namespace }}/{{ template "work-manager.fullname" . }}"
        {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.hubKubeconfigSecret }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
