appVersion: 4.0.12
description: NoSQL document-oriented database.
home: https://github.com/mongodb/mongo
icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
keywords:
- Commercial
- Limited
- amd64
- ppc64le
- s390x
- database
- ICP
kubeVersion: '>=1.9.0-0'
name: icp-mongodb
sources:
- https://github.com/mongodb/mongo
tillerVersion: '>=2.7.0'
version: 3.4.0
