{{- if .Values.tls.enabled -}}

# Licensed Materials - Property of IBM
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "monitoring.fullname" . }}-cert-delete-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "99"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      name: cert
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      hostPID: false
      hostIPC: false
      hostNetwork: false
      containers:
      - name: cert-gen
        image: {{ .Values.curl.image.repository }}:{{ .Values.curl.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add: [NET_ADMIN, NET_RAW, LEASE]
        command:
        - delete_cert.sh
        env:
          - name: releaseNameSpace
            value: {{ .Release.Namespace }}
        volumeMounts:
        - name: script
          mountPath: /usr/local/bin/delete_cert.sh
          subPath: delete_cert.sh
      volumes:
      - name: script
        configMap:
          name: {{ template "monitoring.fullname" . }}-cert-delete
          items:
          - key: delete_cert.sh
            path: delete_cert.sh
            mode: 0777
      restartPolicy: Never
{{- end -}}
