# Licensed Materials - Property of IBM
# @ Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

mode: managed
standalone: true
environment: non-openshift
tls:
  enabled: true
  issuer: icp-ca-issuer
  issuerKind: ClusterIssuer
  sslCiphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
  ca:
    secretName: cluster-ca-cert
    certFieldName: tls.crt
  server:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
  exporter:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
  client:
    existingSecretName: ""
    certFieldName: tls.crt
    keyFieldName: tls.key
imagePullPolicy: IfNotPresent
imagePullSecrets: ""
clusterAddress: 127.0.0.1
clusterPort: 8443
clusterDomain: cluster.local
clusterName: mycluster
crdCreation: false

prometheus:
  enabled: true
  image:
    repository: ibmcom/prometheus
    tag: v2.8.0-build.1
  port: 9090
  scrapeInterval: 1m
  evaluationInterval: 1m
  retention: 24h
  persistentVolume:
    enabled: false
    size: 10Gi
    storageClass: ""
    selector:
      label: ""
      value: ""
  probe:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ## if true, will create rbac role and related rolebinding for k8s resource access
  ##
  rbacRoleCreation: true
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP
  etcdTarget:
    enabled: false
    etcdAddress: ["127.0.0.1"]
    etcdPort: "4001"
    secret: etcd-secret
    tlsConfig: {}
  alerts:
    nodeMemoryUsage:
      enabled: true
      nodeMemoryUsageThreshold: 85
    highCPUUsage:
      enabled: true
      highCPUUsageThreshold: 85
    failedJobs: true
    podsTerminated: true
    podsRestarting: true

alertmanager:
  enabled: false
  image:
    repository: ibmcom/alertmanager
    tag: v0.15.0-build.1
  port: 9093
  persistentVolume:
    enabled: false
    size: 1Gi
    storageClass: ""
    selector:
      label: ""
      value: ""
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  image:
    repository: ibmcom/kube-state-metrics
    tag: v1.3.0-build.1
  port: 80
  probe:
    enabled: true

nodeExporter:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  image:
    repository: ibmcom/node-exporter
    tag: v0.16.0-build.1
  port: 8445
  healthyPort: 8446
  listenPort: 9100
  probe:
    enabled: true

grafana:
  enabled: false
  image:
    repository: "ibmcom/grafana"
    tag: "5.2.0-build.1"
  port: 3000
  persistentVolume:
    enabled: false
    useDynamicProvisioning: true
    size: 1Gi
    storageClass: ""
    existingClaimName: ""
    selector:
      label: ""
      value: ""
  probe:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  configFiles: monitoring.grafanaConfig
  ingress:
    enabled: true
    annotations: {}
  service:
    type: ClusterIP

collectdExporter:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  image:
    repository: ibmcom/collectd-exporter
    tag: v0.4.0-build.1
  service:
    serviceMetricsPort: 9103
    serviceCollectorPort: 25826
  probe:
    enabled: true

configmapReload:
  image:
    repository: ibmcom/configmap-reload
    tag: v0.2.2-build.1

router:
  image:
    repository: ibmcom/icp-management-ingress
    tag: 2.5.0
  subjectAlt: 127.0.0.1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

dashboardController:
  image:
    repository: ibmcom/dashboard-controller
    tag: v1.2.0
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

prometheusOperator:
  image:
    repository: ibmcom/prometheus-operator
    tag: v0.31-build.1
  targetNamespaces:
    releaseNamespaceOnly: true
    namespaces: ""
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

prometheusOperatorController:
  image:
    repository: ibmcom/prometheus-controller
    tag: v1.1.0
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

prometheusConfigReloader:
  image:
    repository: ibmcom/prometheus-config-reloader
    tag: v0.31-build.1

curl:
  image:
    repository: ibmcom/curl
    tag: 4.2.0-build.1

init:
  image:
    repository: ibmcom/icp-initcontainer
    tag: 1.0.0-build.1
