{{- if .Values.tillerIntegration.enabled }}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: helm-crd-admission-controller-cfg
  labels:
    app: helm-crd-admission-controller
webhooks:
  - name: user-check.ibm.com
    clientConfig:
      service:
        namespace: "{{ .Release.Namespace }}"
        name: helm-crd-admission-controller-svc
        path: "/validate"
      caBundle: {{ .Values.helmCRDAdmissionController.caBundle }}
    failurePolicy: Fail
    rules:
      - operations: [ "*" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["helmreleases"]
        scope: "*"
{{- end }}
