# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.alertmanager.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: alertmanager-{{ template "prometheus.fullname" . }}-alertmanager
data:
  alertmanager.yaml: {{ include "alermanagerConfig" . | b64enc | quote }}
{{- end -}}