# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.collectdExporter.enabled -}}

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    {{- if .Values.tls.enabled }}
    prometheus.io/scheme: 'https'
    {{- end }}
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: collectdexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-collectdexporter
spec:
  ports:
  - name: metrics
  {{- if .Values.tls.enabled }}
    targetPort: 8443
  {{- else }}
    targetPort: 9103
  {{- end }}
    port: {{ .Values.collectdExporter.service.serviceMetricsPort }}
    protocol: TCP
  - name: collector
    targetPort: 25826
    port: {{ .Values.collectdExporter.service.serviceCollectorPort }}
    protocol: UDP
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: collectdexporter
    release: {{ .Release.Name }}
  type: ClusterIP

{{- end -}}
