{{- if .Values.elasticsearchExporter.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    {{- if .Values.tls.enabled }}
    prometheus.io/scheme: 'https'
    {{- end }}
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: elasticsearchexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-elasticsearchexporter
spec:
  ports:
  - name: metrics
  {{- if .Values.tls.enabled }}
    targetPort: 8443
  {{- else }}
    targetPort: 9108
  {{- end }}
    port: {{ .Values.elasticsearchExporter.port }}
    protocol: TCP
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: elasticsearchexporter
    release: {{ .Release.Name }}
  type: ClusterIP

{{- end -}}
