{{- if and .Values.grafana.enabled .Values.grafana.persistentVolume.enabled (not .Values.grafana.persistentVolume.existingClaimName) }}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: grafana
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "grafana.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistentVolume.size | quote }}
{{- if .Values.grafana.persistentVolume.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.grafana.persistentVolume.storageClass | quote }}
{{- else }}
  storageClassName: {{ default "" .Values.grafana.persistentVolume.storageClass | quote }}
{{- if .Values.grafana.persistentVolume.selector.label }}
  selector:
    matchExpressions:
      - {key: {{ .Values.grafana.persistentVolume.selector.label }}, operator: In, values: [{{ .Values.grafana.persistentVolume.selector.value }}]}
{{- end }}
{{- end }}
{{- end }}
