{{- if .Values.nodeExporter.enabled -}}
# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    {{- if .Values.tls.enabled }}
    prometheus.io/scheme: 'https'
    {{- end }}
    skip.verify: 'true'
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nodeexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-nodeexporter
spec:
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.port }}
      protocol: TCP
    {{- if .Values.tls.enabled }}
      targetPort: {{ .Values.nodeExporter.port }}
    {{- else }}
      targetPort: {{ .Values.nodeExporter.listenPort }}
    {{- end }}
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: nodeexporter
    release: {{ .Release.Name }}
  type: ClusterIP

{{- end -}}
