# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: v1
appVersion: "1.0"
description: A Helm chart to install subscription, deployable and helm-crd controllers
name: application-manager
version: 0.1.0
