# Default values for application-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

connectionManager: null

clusterName: null
clusterNamespace: null

deployable:
  image:
    repository: quay.io/open-cluster-management/multicluster-operators-deployable
    tag: 1.0.0
    pullPolicy: IfNotPresent

subscription:
  image:
    repository: quay.io/open-cluster-management/multicluster-operators-subscription
    tag: 1.0.0
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 2Gi
