# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{ if .Values.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "topology.fullname" . }}-weave-scope-app
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjAiLCBHaXRDb21taXQ6ImZjMzJkMmYzNjk4ZTM2YjkzMzIyYTM0NjVmNjNhMTRlOWYwZWFlYWQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTAzLTI3VDAwOjEzOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjkuNCIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJkYXJ3aW4vYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwIiwgR2l0VmVyc2lvbjoidjEuMTAuMCtpY3AtZWUiLCBHaXRDb21taXQ6IjljYjY0ZGU0Y2E0ZDAzOWMzNWY0YTI5NzIxYWE1Y2Y3ODc2NDhhMTUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTA0LTI3VDA2OjMyOjE4WiIsIEdvVmVyc2lvbjoiZ28xLjkuMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==",
          "date": "Tue May 08 2018 17:14:07 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    app: {{ template "topology.name" . }}
    chart: {{ template "topology.chart" . }}
    component: "weave-scope-app"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "topology.name" . }}
      component: "weave-scope-app"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "topology.name" . }}
        chart: {{ template "topology.chart" . }}
        component: "weave-scope-app"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ template "topology.fullname" . }}
      containers:
        - name: router
          image: {{ .Values.router.repository }}:{{ .Values.router.tag }}
          imagePullPolicy: {{ .Values.router.pullPolicy }}
          command: ["/opt/ibm/router/entry/entrypoint.sh"]
          ports:
          - name: router
            containerPort: 8080
          volumeMounts:
            - mountPath: "/opt/ibm/router/conf"
              name: weavescope-router-config
            - mountPath: "/opt/ibm/router/server-certs"
              name: weavescope-server-cert
            - mountPath: "/opt/ibm/router/ca-certs"
              name: klusterlet-ca-secret
            - mountPath: "/opt/ibm/router/entry"
              name: weavescope-router-entry
        - name: app
          args:
            - '--mode=app'
            - '--weave=false'
          command:
            - /home/weave/scope
          env:
          - name: DISABLE_BASICAUTH
            value: "true"
          image: "{{ .Values.weave.repository }}:{{ .Values.weave.tag }}"
          imagePullPolicy: {{ .Values.weave.pullPolicy }}
          ports:
            - containerPort: 4040
              protocol: TCP
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      volumes:
        - name: weavescope-router-config
          configMap:
            name: {{ template "topology.fullname" . }}-weavescope-router-nginx-config
        - name: klusterlet-ca-secret
          secret:
            secretName: {{ template "topology.fullname" . }}-ca-cert
        - name: weavescope-server-cert
          secret:
            secretName: {{ template "topology.fullname" . }}-server-secret
        - name: weavescope-router-entry
          configMap:
            name: {{ template "topology.fullname" . }}-weavescope-router-entry-config
            defaultMode: 0744
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{ end }}
