# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "policy.fullname" . }}
  labels:
    app: {{ template "policy.name" . }}
    chart: {{ template "policy.chart" . }}
    component: "compliance"
    release: {{ .Release.Name }}
    controller: "operator"
    heritage: {{ .Release.Service }}
    connectionManager: {{ .Values.connectionManager }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "policy.name" . }}
      component: "compliance"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "policy.name" . }}
        component: "compliance"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "policy.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.0"
    spec:
      serviceAccountName: {{ template "policy.fullname" . }}
      containers:
      - name: policy-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["policy-controller"]
        args:
          - "-logtostderr=true"
          - "--watch-ns={{ .Values.clusterNamespace }}"
          - "--cluster-name={{ .Values.clusterName }}"
          - "--alert-target={{ .Values.cemIntegration.enabled }}"
          - "-v={{ .Values.logLevel }}"
        livenessProbe: null
        readinessProbe: null
      {{- if not (.Values.deployedOnHub) }}
      - name: sync-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["sync-controller"]
        args:
          - "--remote-kubeconfig=/var/run/klusterlet/kubeconfig"
          - "--watch-ns={{ .Values.clusterNamespace }}"
          - "--klusterlet-ns={{ .Release.Namespace }}"
          - "--alert-target={{ .Values.cemIntegration.enabled }}"
          - "-logtostderr=true"
          - "-v={{ .Values.logLevel }}"
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      {{- end }}
      volumes:
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.connectionManager }}-hub-kubeconfig
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
