# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "connection-manager.fullname" . }}
  labels:
    app: {{ template "connection-manager.name" . }}
    chart: {{ template "connection-manager.chart" . }}
    component: "connection-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "connection-manager.name" . }}
      component: "connection-manager"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "connection-manager.name" . }}
        component: "connection-manager"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "connection-manager.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Klusterlet"
        productID: "c18240a57c1c41969d5e81b39435da6c"
        productVersion: "3.2.0"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ template "connection-manager.fullname" . }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        args:
          - "/klusterlet-operator"
          - "--operator-configmap={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}"
          - "--cert-store-secret={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}-cert-store"
          - "--cluster={{ .Values.clusterNamespace }}/{{ .Values.clusterName }}"
          - "--klusterlet-secret={{ .Release.Namespace }}/{{ template "connection-manager.fullname" . }}-hub-kubeconfig"
          - "--klusterlet-labels=controller=operator"
        {{- if gt .Values.replicas 1.0 }}
          - "--leader-elect=true"
        {{- end }}
        {{- if .Values.globalView.enabled }}
          - "--enable-global-view"
          - "--collector-labels={{ .Values.globalView.collectorLabels }}"
        {{- end}}
        livenessProbe: null
        readinessProbe: null
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}

