# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

imagePullPolicy: IfNotPresent
# imagePullSecret: myregistrykey

ocp: true

caCertIssuer: null
issuerKind: ClusterIssuer
  
config:
  cloud_env: "openshift"

tolerations:
- key: "dedicated"
  operator: "Exists"
  effect: "NoSchedule"


cisCrawler:
  enabled: true
  crawlInterval: 86400
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 512Mi

minio:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 1024Mi
  persistence:
    enabled: false
    size: "20Gi"
    storageClass: "-"

drishti:
  config:
    cloud_env: "openshift"
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"

minioCleaner:
  name: "minioCleaner"
# The buckets name with survival time
  preserve_buckets: ciscos-host:180d cis-k8s:180d
  schedule: "59 23 * * *"
  resources:
    requests:
      memory: "128Mi"
    limits:
      memory: 512Mi

cisController:
  name: cis-controller
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: 512Mi

global: 
  fullnameOverride: endpoint-cisctrl
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    cis_controller: quay.io/open-cluster-management/cis-controller:3.6.0
    drishti_cis: quay.io/open-cluster-management/drishti-cis:3.4.0
    cis_crawler: quay.io/open-cluster-management/cis-crawler:3.6.0
    img_minio: quay.io/open-cluster-management/img-minio:RELEASE.2019-04-09T01-22-30Z.3
    img_minio_mc: quay.io/open-cluster-management/img-minio-mc:RELEASE.2019-04-03T17-59-57Z.3
