# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

enabled: true
replicas: 1
clusterName: null
clusterNamespace: null

bootstrapConfig:
  hubSecret: kube-system/klusterlet-bootstrap

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

logLevel: 5

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    multicloud_manager: quay.io/open-cluster-management/multicloud-manager:3.2.0