apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ template "tiller.fullname" . }}
  labels:
    app: {{ template "tiller.name" . }}
    chart: {{ template "tiller.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ca:
    secretName: {{ template "tiller.fullname" . }}-ca-cert
