# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "topology.fullname" . }}-ca-cert
  labels:
    app: {{ template "topology.name" . }}
    chart: {{ template "topology.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  secretName: {{ template "topology.fullname" . }}-ca-cert
  issuerRef:
    name: {{ .Values.caCertIssuer }}
    kind: ClusterIssuer
  commonName: {{ template "topology.fullname" . }}
  isCA: true
  organization:
  - IBM
  dnsNames: null
