# Default values for application-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
org: open-cluster-management

enabled: true

hubKubeconfigSecret: null

clusterName: null
clusterNamespace: null

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 2Gi

leaseName: application-manager

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    multicluster_operators_subscription: quay.io/open-cluster-management/multicluster-operators-subscription:1.0.0
    klusterlet_addon_lease_controller: ""